name: ciao
run-name: ciao da parte di ${{ github.actor }}
on: [push]
jobs:
  ciao:
    runs-on: ubuntu-latest
    steps:
      - run: |
          ls -la
          cd javademo/my-app
          mvn install
      - run: echo "lesgoski"
  verifica-cartella:
    runs-on: ubuntu-latest
    steps:
      - run: |
          ls -la
      - run: echo "verifica cartella"